### ISSUE TITLE
Optimise BibTeX expansion

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam-bibtex#10]
We need to find a better way to modify the `org-capture-templates`.  We need to find a way to insert ourselves in the `org-capture` process.  Maybe simulate an `org-capture` template-selection just to get the key, and then only expand the assoc'd template?

https://github.com/zaeph/org-roam-bibtex/blob/0a5a5d6945097fbe8e36dbf586c469acdf766f08/org-roam-bibtex.el#L430-L438

**Comment by myshevchuk** [comment]
A way to go, yes. But then we will have to give up the interactive capture process. Which is not something essential for note taking, yet there must be a very good reason to sacrifice it. The main benefit of having an interactive capture process is that it can be cancelled in the middle and no file will be created.

**Comment by myshevchuk** [comment]
Do you think this optimization may be postponed until it really becomes an experienced or reported issue?

**Comment by Zaeph** [comment]
> Do you think this optimization may be postponed until it really becomes an experienced or reported issue?

Yeah, that's why I've created this issue to keep it in our mind.  If [someone with a hundred-or-so templates](https://xkcd.com/1172/) comes around and reports some slow-down after running `org-capture`, we'll know it's time to optimise.

**Comment by myshevchuk** [comment]
I'm thinking about temporary advising some `org-capture` internals. Not sure if it's a good practice.

**Comment by Zaeph** [comment]
> I'm thinking about temporary advising some `org-capture` internals. Not sure if it's a good practice.

I don't know, but it might be worth looking into.

**Comment by myshevchuk** [comment]
By the way, template pre-formatting now works with full repertoire of `org-capture` template options, that is a string, a file and a function.
```
(setq org-roam-capture-templates
      '(("r" "reference" plain (function org-roam-capture--get-point)
         (file "/path/to/template.org")
         :file-name "test/${citekey}"
         :head "#+TITLE: ${title}\n"
         :unnarrowed t)))
```
Contents of "template.org":
```
#+ROAM_KEY: %^{citekey}
#+PROPERTY: type %^{type}
#+TAGS: %^{keywords}
#+PROPERTY: authors %^{author}

In this %\2 %\4 concluded that %?

fullcite:%\1
```

**Comment by Zaeph** [comment]
> By the way, template pre-formatting now works with full repertoire of `org-capture` template options, that is a string, a file and a function.

Oh that is splendid, thanks for adding that in!  I didn't even know you could do that.

**Comment by Zaeph** [comment]
> By the way, template pre-formatting now works with full repertoire of `org-capture` template options, that is a string, a file and a function.

I've referenced it in `README.md`: e2026ab.
