### ISSUE TITLE
Opening bibtex entry opens buffer to dired instead of opening pdf

### ISSUE THREAD

**Issue by y2klol** [org-roam/org-roam-bibtex#100]
GNU Emacs 26.3
org-roam-bibtex    20200912.1538 installed

* Problem:
Selecting "2. Open pdf" in the helm bibtex menu for an entry opens the buffer to dired / directory. 

![Screenshot_20200927_234503](https://user-images.githubusercontent.com/7161748/94366425-88744c80-011b-11eb-8cd2-90c6a1dbc70b.png)

![Screenshot_20200927_234839](https://user-images.githubusercontent.com/7161748/94366500-1b14eb80-011c-11eb-9981-58d80a70e5a6.png)

![Screenshot_20200927_234631](https://user-images.githubusercontent.com/7161748/94366467-c5404380-011b-11eb-9d08-33ed68f292c1.png)

* Expected Result:
Selecting "2. Open pdf" in helm bibtex menu should open the pdf in emacs using pdf tools. 

* Steps to resolve the issue:
** Absolute link in bibtex file
I changed the bibtex entry "file" property to be an absolute path rather than a relative path. 
Compare: 
```
@article{wolfmoon12,
title = {"{{The Moon}} over the {{Mountain}}": {{Stories}} by {{Atsushi Nakajima}} by {{Paul McCarthy}} and {{Nobuko Ochner}} (Review)},
shorttitle = {"{{The Moon}} over the {{Mountain}}"},
author = {Wolf, Charles De},
date = {2012},
journaltitle = {Monumenta Nipponica},
volume = {67},
pages = {371–374},
publisher = {{Sophia University}},
issn = {1880-1390},
doi = {10.1353/mni.2012.0021},
file = {files/1450/Wolf - 2012 - The Moon over the Mountain Stories by Atsushi N.pdf},
langid = {english},
number = {2}
}
```
to

```
@article{wolfmoon12,
  title = {"{{The Moon}} over the {{Mountain}}": {{Stories}} by {{Atsushi Nakajima}} by {{Paul McCarthy}} and {{Nobuko Ochner}} (Review)},
  shorttitle = {"{{The Moon}} over the {{Mountain}}"},
  author = {Wolf, Charles De},
  date = {2012},
  journaltitle = {Monumenta Nipponica},
  volume = {67},
  pages = {371--374},
  publisher = {{Sophia University}},
  issn = {1880-1390},
  doi = {10.1353/mni.2012.0021},
  file = {/home/solomon/Org/slipbox/bib/files/1450/Wolf - 2012 - The Moon over the Mountain Stories by Atsushi N.pdf},
  langid = {english},
  number = {2}
}
```
After doing changing the bibtex entry, restarting emacs and citing the entry again, I get to the helm bibtex menu and select "2. Open pdf" and it attempts to open the pdf in my OS default pdf viewer (okular) 

![](https://aws1.discourse-cdn.com/free1/uploads/orgroam/original/1X/71b7c4f1e6a91c1672d75ead62a46a9d323d24fb.png)

It will still open the other buffer as dired / directory. 

** Remove Template from helm

```
(use-package helm-bibtex
  :ensure t
  :init (autoload 'helm-bibtex "helm-bibtex" "" t)
  :config
  (setq bibtex-completion-notes-path "~/Org/slipbox/bib/bibnotes/")
  (setq reftex-default-bibliography '("~/Org/slipbox/bib/bib.bib"))
  (setq bibtex-completion-bibliography '("~/Org/slipbox/bib/bib.bib"))
  (setq bibtex-completion-pdf-field "file")
  (setq bibtex-completion-notes-template-multiple-files
	(concat
	 "#+TITLE: ${title}\n"
         "#+ROAM_KEY: cite:${=key=}\n"
	 "* TODO Notes\n"
	 ":PROPERTIES:\n"
	 ":Custom_ID: ${=key=}\n"
	 ":NOTER_DOCUMENT: ${file}\n"
	 ":AUTHOR: ${author-abbrev}\n"
	 ":JOURNAL: ${journaltitle}\n"
	 ":DATE: ${date}\n"
	 ":YEAR: ${year}\n"
	 ":DOI: ${doi}\n"
	 ":URL: ${url}\n"
	 ":END:\n\n"
  ))
  ;;  (setq org-ref-get-pdf-filename-function (lambda (key) (car (bibtex-completion-find-pdf key)))))
  )
```
was my original helm-bibtex package but I changed it to below after being told it's redundant and might be conflicting. 

```
(use-package helm-bibtex
  :ensure t
  :init (autoload 'helm-bibtex "helm-bibtex" "" t)
  :config
  (setq bibtex-completion-notes-path "~/Org/slipbox/bib/bibnotes/")
  (setq reftex-default-bibliography '("~/Org/slipbox/bib/bib.bib"))
  (setq bibtex-completion-bibliography '("~/Org/slipbox/bib/bib.bib"))
  (setq bibtex-completion-pdf-field "file")
  ;;  (setq org-ref-get-pdf-filename-function (lambda (key) (car (bibtex-completion-find-pdf key)))))
  )
```
This did not resolve the issue. 

** bibtex-completion-pdf-open-function

![](https://aws1.discourse-cdn.com/free1/uploads/orgroam/original/1X/18581effcb68dfcf683db1ae672460b42d8c099d.png)

Looking at the value of bibtex-completion-pdf-open-function to see if it was a odd entry, However, the value is still find-file.

** Something wrong with pdf-tools
I thought that maybe the issue is with pdf-tools as a whole. However, using find-file (C-x C-f) and manually locating the file and opening it results in emacs opening the file just fine

![Screenshot_20200928_000842](https://user-images.githubusercontent.com/7161748/94366980-d5a5ed80-011e-11eb-8af2-1588ee52e687.png)

* Org Roam File
```
; Roam Research Emacs
(use-package org-roam
  :ensure t
  :hook
  (after-init . org-roam-mode)
  :custom
  (org-roam-directory "~/Org/slipbox/")
  :bind (:map org-roam-mode-map
	      (("C-c n l" . org-roam)
               ("C-c n f" . org-roam-find-file)
               ("C-c n g" . org-roam-graph))
              :map org-mode-map
              (("C-c n i" . org-roam-insert))
              (("C-c n I" . org-roam-insert-immediate))))

;; Allows for Org-roam to display in a web browser
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))

;; Add bibliography and bibliographical notes to Org Roam
(use-package org-roam-bibtex
  :ensure t
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :bind (:map org-mode-map
              (("C-c n a" . orb-note-actions)))
  :config
  (setq orb-preformat-keywords
	'(("citekey" . "=key=") "title" "url" "file" "author-or-editor" "keywords"))
  (setq orb-process-file-field t)
  (setq orb-file-field-extensions "pdf")
  (setq orb-templates
	'(("r" "ref" plain (function org-roam-capture--get-point)
	   ""
	   :file-name "literature/${citekey}"
	   :head "#+TITLE: ${citekey}: ${title}\n#+ROAM_KEY: ${ref}\n- tags ::\n- keywords :: ${keywords}\n* ${title}\n:PROPERTIES:\n:Custom_ID: ${citekey}\n:URL: ${url}\n:AUTHOR: ${author-or-editor}\n:NOTER_DOCUMENT: ${file}\n:NOTER_PAGE:\n:END:"))))

(use-package company-org-roam
  :ensure t
  :config
  (push 'company-org-roam company-backends))
(provide 'init-orgroam) 
```

**Comment by myshevchuk** [comment]
This is not an `org-roam-bibtex` issue. Org Roam BibTeX uses `bibtex-completion` as a backend but is not affiliated with it or `helm-bibtex` for that matter. Please report problems with `helm-bibtex` at https://github.com/tmalsburg/helm-bibtex

**Comment by myshevchuk** [comment]
@y2klol, I'm closing this issue because it has nothing to do with ORB. Please continue the discussion where you started it at https://org-roam.discourse.group/t/need-help-getting-noter-pdfs-and-org-roam-bibtex-to-work/794

**Comment by y2klol** [comment]
Thank you for informing the proper location to report the issue and for linking the discussion. Hopefully I will solve this so people can use this issue as a reference if they experience the same issue.
