### ISSUE TITLE
Unable to choose template for bibtex entries with no file

### ISSUE THREAD

**Issue by anaxonda** [org-roam/org-roam-bibtex#108]
Hello,

I am unable to choose a template for bibtex entries that don't have a `file` field. I am able to choose templates for bibtex entries that have a file field.

I have three templates set up, one for journal articles, one for ebooks, and one for physical books. It seems like org-roam-bibtex is choosing my `ref-science` template, and failing because there is no `file` field. I would prefer to choose my `paper books` template.

Here are my templates:

`(setq orb-templates
        '(("r" "ref-science" plain (function org-roam-capture--get-point)
         ""
         :file-name "${citekey}"
         :head "#+TITLE: ${citekey}: ${title}\n#+ROAM_KEY: ${ref}

- tags ::
- keywords :: ${keywords}

* ${title}
:PROPERTIES:
:Custom_ID: ${citekey}
:URL: ${url}
:AUTHOR: ${author-or-editor}
:NOTER_DOCUMENT: ${file}
:NOTER_PAGE:
:END:")
          ;;template for ebooks
      ("b" "ebooks" plain (function org-roam-capture--get-point)
         ""
         :file-name "${citekey}-${slug}"
         :head "#+TITLE: ${author-or-editor}: ${title}\n#+ROAM_KEY: ${ref}

- tags ::
- keywords :: ${keywords}

* ${title}
:PROPERTIES:
:Custom_ID: ${citekey}
:URL: ${url}
:AUTHOR: ${author-or-editor}
:NOTER_DOCUMENT: ${file}
:NOTER_PAGE:
:END:")
   ;; template for paper books
       ("p" "paper books" plain (function org-roam-capture--get-point)
                ""
                :file-name "${citekey}-${slug}"
                :head "#+TITLE: ${author-or-editor}: ${title}\n#+ROAM_KEY: ${ref}
- tags ::
- keywords :: ${keywords}")
        ))
  ) `

Here is an example bibtex entry that does not work:

@book{crononChangesLandIndians2003,
  title = {Changes in the {{Land}}: {{Indians}}, {{Colonists}}, and the {{Ecology}} of {{New England}}},
  shorttitle = {Changes in the {{Land}}},
  author = {Cronon, William},
  date = {2003-09-01},
  edition = {Revised Edition},
  publisher = {{Hill and Wang}},
  location = {{New York}},
  isbn = {978-0-8090-1634-1},
  langid = {english},
  pagetotal = {284}

Here is the debug error: 
Debugger entered--Lisp error: (void-function nil)
  nil("${file}")
  replace-regexp-in-string("\\${file}" nil "#+TITLE: ${citekey}: Changes in the Land: Indians,..." t t)
  s-replace("${file}" nil "#+TITLE: ${citekey}: Changes in the Land: Indians,...")
  orb--preformat-template(("r" "ref-science" plain #'org-roam-capture--get-point "" :file-name "${citekey}" :head "#+TITLE: ${citekey}: Changes in the Land: Indians,...") (("=key=" . "crononChangesLandIndians2003") ("=type=" . "book") ("title" . "Changes in the {{Land}}: {{Indians}}, {{Colonists}...") ("shorttitle" . "Changes in the {{Land}}") ("author" . "Cronon, William") ("date" . "2003-09-01") ("edition" . "Revised Edition") ("publisher" . "{Hill and Wang}") ("location" . "{New York}") ("abstract" . "The book that launched environmental history now u...") ("isbn" . "978-0-8090-1634-1") ("langid" . "english") ("pagetotal" . "284")))
  orb-edit-notes("crononChangesLandIndians2003")
  orb-edit-notes-ad(("crononChangesLandIndians2003"))
  apply(orb-edit-notes-ad ("crononChangesLandIndians2003"))
  bibtex-completion-edit-notes(("crononChangesLandIndians2003"))
  ivy-bibtex-edit-notes(("2003-09-01 Cronon, William Changes in the Land: In..." ("date" . "2003-09-01") ("author" . "Cronon, William") ("title" . "Changes in the {{Land}}: {{Indians}}, {{Colonists}...") ("=type=" . "book") ("=key=" . "crononChangesLandIndians2003")))
  ivy-call()

What am I missing here? Thanks!

**Comment by myshevchuk** [comment]
Thank you! Please upgrade to the latest version.

**Comment by anaxonda** [comment]
Excellent, many thanks for the quick fix!
