### ISSUE TITLE
Allow for directly inserting org-roam links to bibtex files

### ISSUE THREAD

**Issue by garrettdreyfus** [org-roam/org-roam-bibtex#110]
I've been using org-roam-bibtex for about two months now. My workflow for using it is pretty much exactly the way it is demonstrated by the GIF in the README. I use a keybinding to org-ref-helm-insert-cite-link to search through my bibtex file and insert citation. I then select the citation and "add notes" which creates an org-roam card for me. The only sticking point for me is that I much prefer having org-roam links lying around than "cite:___" links, so I usually delete the cite key and replace it with a reference to the associated org-roam card I just created. 

Could a function be created to replace org-ref-helm-insert-cite-link  that would allow me to search through my bibtex file, select a paper, and then immediately create an org-roam card and insert the link? Essentially, something that would act like org-roam-insert but allow me to choose from my bibliography?

Thank you,

Garrett

P.S. This package is amazing thank you so much!

**Comment by myshevchuk** [comment]
Hi, thank you for your request and appreciation! I've got a working prototype and will merge into the development branch for testing anytime soon.
Best,
Michael

**Comment by myshevchuk** [comment]
Hi, I have just added a PR #111 with the new functionality `orb-insert`. The pull request has been merged into the `develop` branch so you can more easily retrieve it. If you could please test it and send me a feedback, I would be very grateful. I will merge it into `master` so that it will appear on Melpa after I do more testing and some clean-up to the code, probably on this weekend.

Check the docstrings to the following functions and variables on how to use it, it's pretty configurable:

#### Commands:
- orb-insert

#### Customization options:
- orb-insert-frontend
- orb-insert-link-description
- orb-insert-generic-candidates-format
- orb-edit-notes-note-exists-hook

**Comment by garrettdreyfus** [comment]
Hey!

Thank's so much! When I tried to install from the develop branch running orb-insert resulted in this error message:

```
Symbol's function definition is void: map
```

When I use the master branch everything works like normal.

Thanks,

Garrett

**Comment by myshevchuk** [comment]
Hi! Thanks a lot. This should be fixed now in develop

**Comment by myshevchuk** [comment]
So, a short summary.

Call interactively `orb-insert`. An interface to select a bibtex entry from `bibtex-completion-bibliography` will be presented. Choose an entry and press return. A new link should be inserted. If the note does not exist yet, it will be created in a way similar to when you use "Edit notes" from Org-ref or Helm-bibtex menu.

The interface to select a bibtex entry can be controlled by setting `orb-insert-frontend`. Helm-bibtex, ivy-bibtex or a simple "generic" completion  interface can be used.

It is also possible to control what will be used as the link's description by setting `orb-insert-link-description`. Currently there are three options:
```
'title      => [[file:path/to/note.org][Entry Title]]
'citekey    => [[file:path/to/note.org][citekey]]
'citation   => cite:citekey
```

It is possible to override the default specified in `orb-insert-link-description` by passing a numerical argument to `orb-insert`:
* `C-1 M-x orb-insert`   => title
* `C-2 M-x orb-insert`  => citekey
* `C-3 M-x orb-insert` => citation

In future, a general mechanism will be added to use an arbitrary BibTeX field as a link description.

Check also the docstrings for a few more options.

Please expect glitches and feel free to request changes or additional customization options.

**Comment by garrettdreyfus** [comment]
Wow! It works amazing! Thank you so much!

**Comment by myshevchuk** [comment]
Great! I'll reopen the issue till the PR is merged into master.

**Comment by myshevchuk** [comment]
Merge into master.
