### ISSUE TITLE
Edit notes does not work in helm-bibtex when file exists

### ISSUE THREAD

**Issue by weidtn** [org-roam/org-roam-bibtex#122]
When I'm creating a new note in `helm-bibtex`, the org-capture template appears and can save it to create the file. But I can't open the existing file from `helm-bibtex` when selecting the `Edit Notes` option. It just closes `helm-bibtex` and nothing appears.

**Comment by myshevchuk** [comment]
Hi thanks a lot! This bug was introduced in the recent refactoring. Sorry for that.
