### ISSUE TITLE
Auto-select a template when only one defined

### ISSUE THREAD

**Issue by czikus** [org-roam/org-roam-bibtex#124]
Currently, when creating a note, `org-capture-select-template` is called asking for a template to use. I have only one template defined for all bibtex notes and this adds an unnecessary step to the note creation process. Would it be possible to skip this step when only one template is defined in `orb-templates`?

**Comment by myshevchuk** [comment]
Hi, thank you! Should be fixed now.

**Comment by czikus** [comment]
Works great. Thanks!
