### ISSUE TITLE
`user-error: No #+ROAM_KEY found in current buffer`

### ISSUE THREAD

**Issue by junwei-wang** [org-roam/org-roam-bibtex#127]
ORB Note Action does not work on macOS Big Sur + Doom Emacs.
The mini buffer says `user-error: No #+ROAM_KEY found in current buffer`.

Example file:

```
#+TITLE: Computing aggregation function minimum/maximum using homomorphic encryption schemes in wireless sensor networks (WSNs)
#+ROAM_KEY: cite:ICWN:ErtaulK07
#+ROAM_TAGS: crypto fhe
```

**Comment by myshevchuk** [comment]
Hi, I'm on Big Sur + Doom and cannot reproduce your issue. Everything's working perfectly fine. I will need more specific information, e.g. the BibTeX entry, the exact commands you run, the `org-roam-bibtex` and `org-roam` commits you are at and so on.

**Comment by junwei-wang** [comment]
- BibTeX entry:
	
    ```
	@inproceedings{ICWN:ErtaulK07,
	  author          = {Levent Ertaul and Vaidehi Kedlaya},
	  editor          = {Hamid R. Arabnia and Victor A. Clincy and Laurence Tianruo
	                  Yang},
	  title           = {Computing Aggregation Function Minimum/Maximum using
	                  Homomorphic Encryption Schemes in Wireless Sensor Networks
	                  (WSNs)},
	  booktitle       = {Proceedings of the 2007 International Conference on
	                  Wireless Networks, June 25-28, 2007, Las Vegas, Nevada, {USA}},
	  pages           = {186--192},
	  publisher       = {{CSREA} Press},
	  year            = 2007,
	  timestamp       = {Mon, 09 Feb 2009 10:38:02 +0100},
	  biburl          = {https://dblp.org/rec/conf/icwn/ErtaulK07.bib},
	  bibsource       = {dblp computer science bibliography, https://dblp.org}
	}
	```


- I run `orb-note-actions` in a ORB note in the org-roam directory with a file name `ICWN:ErtaulK07` and the following contents:
   ```
	#+TITLE: Computing aggregation function minimum/maximum using homomorphic encryption schemes in wireless sensor networks (WSNs)
	#+ROAM_KEY: cite:ICWN:ErtaulK07
	#+ROAM_TAGS: crypto fhe
   ```
	(In fact, this command does not work for every ORB note I have)

- org-roam version: `org-roam-20201128.1144`
- ORB version: `org-roam-bibtex-20201127.2234`

**Comment by myshevchuk** [comment]
I still cannot reproduce this with your entry.

![Screenshot 2020-12-03 at 09 41 22](https://user-images.githubusercontent.com/24212814/100984990-b6c33d80-354b-11eb-880e-5834ae994bce.png)

There were some issues about `#ROAM_KEY:` recently as far as I remember. So if anything, it's most probably related to Org Roam, not ORB. Did you try to rebuild your Org Roam database, `M-x org-roam-db-build-cache`?

A bug trace would be very helpful. Turn on `toggle-debug-on-error` and try running the command again.

**Comment by junwei-wang** [comment]
Hi, thank you very much for your instant reply.

- `org-roam-db-build-cache` does resolve this issue.
- `toggle-debug-on-erro` prints nothing more than `user-error: No #+ROAM_KEY found in current buffer` in my minibuffer.

**Comment by myshevchuk** [comment]
Try purging Org, Org Roam and ORB from `$DOOM/.local/straight/build-xx.x/`. Quit Emacs and run `doom sync`. As a last resort, try purging the whole directory `$DOOM/.local/straight/build-xx.x/`.

**Comment by junwei-wang** [comment]
I tried to rebuild doom and tried to restart my computer, the issue still exists.

Thank you very much anyway.

**Comment by junwei-wang** [comment]
BTW, I paste my Doom `package.el`:

```
;;; org-roam
;;; org-roam-bibtex
(package! org-roam-bibtex
  :recipe (:host github :repo "org-roam/org-roam-bibtex"))
;; When using org-roam via the `+roam` flag
(unpin! org-roam company-org-roam)

;;; org-roam-server
(package! org-roam-server)

;;;
(package! helm-bibtex)
```

**Comment by myshevchuk** [comment]
The error is indeed emanated by `orb-note-actions` when the citation key is nil. This function relies on `org-roam--extract-refs` to extract the value of the citekey from `#+ROAM_KEY: citekey`. For some reason, `org-roam--extract-refs` is not working properly in your environment. By expecting its code, I would say this function will return nil when the `cite:`-type org-links are not defined. These citation links are defined by the package `org-ref`. Is it possible that you do not have `org-ref` installed on your computer, or that it is not (properly) loaded during the run time?

**Comment by junwei-wang** [comment]
Yes, you are right. Thank you very much. Sorry for this stupid mistake.

For new users encountering same issue, here is my `package.el` 

```elisp
;;;;;;;;; org-roam-bibtex (ORB)
(package! org-roam-bibtex
  :recipe (:host github :repo "org-roam/org-roam-bibtex"))
;; When using org-roam via the `+roam` flag
(unpin! org-roam company-org-roam)

;;; ORB dependencies
(package! org-ref)
(package! helm-bibtex)
```
and `config.el`

```elisp
;;;;;;;;; Bibliography
;;; helm-bibtex
(setq bibtex-completion-bibliography '("/path/to/your_first.bib"
                                       "/path/to/2nd.bib")
      bibtex-completion-library-path '("/path/to/pdfs"))

;;; org-ref
(setq reftex-default-bibliography bibtex-completion-bibliography)

;; see org-ref for use of these variables
(setq org-ref-default-bibliography bibtex-completion-bibliography
      org-ref-pdf-directory "/path/to/pdfs")

```

**Comment by junwei-wang** [comment]
Something irrelevant: 

How to add note directly in pdf as in https://youtu.be/Wy9WvF5gWYg?t=380.
What command / key-binding was used in the video?

**Comment by myshevchuk** [comment]
It's perfectly fine to be a beginner. Also, `org-roam-bibtex` softly depends on `org-ref`, and I believe this is not stated in the README. I will also improve the error message, because it did not reflect what was going on, which may be considered a bug. So thank you and I'm glad you've solved your issue.

It is a different kind of notes in the video. The package is called `org-noter`. It is not affiliated with ORB, but ORB has offers minimal integration with it.

**Comment by junwei-wang** [comment]
Thank you for you kind reply. 
I find this package and enjoy using it now.
