### ISSUE TITLE
orb-insert with bibtex keys?

### ISSUE THREAD

**Issue by cryoguy** [org-roam/org-roam-bibtex#128]
orb note works fine with `org-ref` citation and `org-noter` in my system.  But when I evoke `orb-insert`, it only provides me with a list of bibtex keys. After I pick the key, I will be redirected to orb template option buffer.   

Can `orb-insert` evoke the `helm-bibtex` way of showing bibtex library as `org-ref` does? or it is just my configuration?

**Comment by myshevchuk** [comment]
The command `orb-insert` is meant to be used to insert links to existing notes. If the note does not exist yet, you will be prompted to create a new one, i.e. "redirected to orb template option buffer". If you set `orb-insert-interface` to `helm-bibtex`, you will also be able to "evoke the helm-bibtex way of showing bibtex library as org-ref does".

If you don't have any issues with `org-roam-bibtex`, please consider asking questions on [Slack](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) or [Discourse](https://org-roam.discourse.group/).
