### ISSUE TITLE
about org-noter notes directory

### ISSUE THREAD

**Issue by cryoguy** [org-roam/org-roam-bibtex#129]
My org-noter notes reside in my references folder, which is different from the org-roam directory.   Is this going to be a problem for org-roam to locate my notes?

**Comment by myshevchuk** [comment]
Hi, how is this relevant to `org-roam-bibtex`? Unless you have issues with `org-roam-bibtex`, please consider asking Org Roam questions on [Slack](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) or [Discourse](https://org-roam.discourse.group/)
