### ISSUE TITLE
slug not correctly set when creating a new note

### ISSUE THREAD

**Issue by brabalan** [org-roam/org-roam-bibtex#130]
Although I have `orb-slug-source` set to `'title`, I'm still being asked for a slug when creating a note. I think the issue is at https://github.com/org-roam/org-roam-bibtex/blob/master/org-roam-bibtex.el#L789, the line `(slug. ,(funcall` should be `(slug . ,(funcall` (with a space before the `.`).

**Comment by myshevchuk** [comment]
Thanks a lot! Fixed by #131
