### ISSUE TITLE
PDF-Scrapper: Consistent formatting between headings (Newline)

### ISSUE THREAD

**Issue by j-steinbach** [org-roam/org-roam-bibtex#151]
> One thing I noticed - is there a way to get an empty line between [12] and **In BibTeX file? And why is there no empty line between ** In Org Roam database and #+name: in-roam? The styles are a bit mixed. (Not inserting empty lines is fine too, but it should be consistent).

It drove me crazy back then when I was writing this part because I couldn't manage to have these newlines in place. ORB actually puts them, but they mysteriously disappear, probably slurped by Org mode when it inserts new headlines. This is something that still bothers me, although I'm now used to put those newlines by hand. Feel free to open an issue for this, maybe this time I'll have more luck.

_Originally posted by @myshevchuk in https://github.com/org-roam/org-roam-bibtex/issues/141#issuecomment-748630472_

**Comment by myshevchuk** [comment]
This issue is fixed in the [scrapper-save](https://github.com/org-roam/org-roam-bibtex/tree/scrapper-save) branch. Since this fix is applied in a place that was considerably changed by the new functionality that will be soon merged into master, I don't provide a fix for the master branch to avoid merging hassle.

**Comment by j-steinbach** [comment]
Sorry for answering just now, am quite busy :skull: 

Basically I can wait until this is in master? Or is there anything you need me to do/try?

**Comment by myshevchuk** [comment]
Yes, you can wait until this is in master or switch to the [save-scrapper](https://github.com/org-roam/org-roam-bibtex/tree/scrapper-save) branch, where it is already fix. That branch should be usable now.
