### ISSUE TITLE
orb-file-field-extensions is being ignored

### ISSUE THREAD

**Issue by PhDyellow** [org-roam/org-roam-bibtex#164]
**Describe the bug**
orb-file-field-extensions is being ignored. I am being asked to choose between a pdf and a html file, even though I have (setq orb-file-field-extensions "pdf") in my config.

**To Reproduce**
1. include (setq orb-file-field-extensions "pdf") in my config file.
2. Set up a bibtex entry with a ".pdf" and a ".html" file attachment. I am using Zotero to export to bibtex.
3. Using a template with (orb-process-file-field), create a new note from the helm interface

**Expected behavior**
Because of (setq orb-file-field-extensions "pdf"), the "html" should be ignored, and the pdf file should be chosen without asking.

**ORB configuration**
1. Doom emacs: `(package! org-roam-bibtex  :recipe (:host github :repo "org-roam/org-roam-bibtex"))`

2. ORB options set to non-default values (e.g. `orb-templates`)

```
(use-package! org-roam-bibtex
  :after (org-roam)
  :hook (org-roam-mode . org-roam-bibtex-mode)
 :config
  (setq
   orb-preformat-templates t 
  orb-preformat-keywords
  '("=key="  "title" "citekey" "keywords" "url"
    ;"file"
    "author"
    "editor"
    )
   orb-process-file-keyword t
orb-file-field-extensions "pdf"
```

**Environment (please complete the following information):**
 - ORB version: 569df3d master origin/master (fix) orb-notes-cache for orb-find-note-file
  - Org Mode version: 9.5
 - Emacs framework [e.g. Doom, Spacemacs, Prelude, none]: Doom
 - Emacs version [e.g. 26.3, 27.1]: 28
 - OS: [e.g. Linux, macOS, Windows]: Linux

**Screenshots**

**Comment by PhDyellow** [comment]
I did some testing, and found that I could get it to work again by removing the `lambda` from around `when-let` in `orb-process-file-field`, line 144 in `orb-core.el` introduced in 9ba1506.

from 
```
(setq paths (--filter
                       (lambda ()
                         (when-let ((extension (file-name-extension it)))
                           (member-ignore-case extension extensions)))
                       paths)))
```
to
```
          (setq paths
                (--filter
                 (when-let ((extension (file-name-extension it)))
                   (member-ignore-case extension extensions))
                 paths)))

```

**Comment by myshevchuk** [comment]
Thanks a lot! No idea why I put that lambda there.
