### ISSUE TITLE
Differences between plain org-ref notes with backlinks and org-roam-bibtex

### ISSUE THREAD

**Issue by AtomicNess123** [org-roam/org-roam-bibtex#170]
Generally, the only difference between using Org-roam-bibtex to create notes associated to a bibtex entry and using the org-ref note creation tool, would be that in the latter we have to org-roam-insert our backlinks manually (and each note would be created as a heading in an orgmode file? Just trying to figure out differences. Thanks for the package.

**Comment by myshevchuk** [comment]
Hi, I'm glad you like the package. Unless you have issues with ORB or would like to request a new feature, please use our [Slack channel](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) and [Discourse board](https://org-roam.discourse.group/) to ask general questions.
