### ISSUE TITLE
Don't hard set the value of org-ref-notes-function

### ISSUE THREAD

**Issue by bigodel** [org-roam/org-roam-bibtex#173]
as referenced in #172, more specifically in 1. of [this](https://github.com/org-roam/org-roam-bibtex/issues/172#issuecomment-785224914) comment.

**Comment by myshevchuk** [comment]
> it would just be the case of storing the
value of the variable in another variable and resetting it when the mode is
unloaded, right?

Basically yes, just the edge case when Org-ref is not loaded yet must be taken into account. ORB redefines `org-ref-notes-function` in `org-roam-bibtex-mode`, it is perfectly legitimate not to have Org-ref loaded yet, unlike issue #172.

**Comment by bigodel** [comment]
> Basically yes, just the edge case when Org-ref is not loaded yet must be taken into account. ORB redefines `org-ref-notes-function` in `org-roam-bibtex-mode`, it is perfectly legitimate not to have Org-ref loaded yet, unlike issue #172.

ok great, will try to solve it in a PR.

**Comment by myshevchuk** [comment]
This is not longer relevant for Org-ref v3, but the provided fix is general and also works for Org-ref v2 for those who still use the old version.
