### ISSUE TITLE
Make `org-roam-bibtex-templates` more user-friendly

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam-bibtex#18]
As discussed in #16, `org-roam-bibtex-templates` and `org-roam-capture-templates` share the same syntax, so much so that, at an early stage, we only used `capture` to generate the templates.

Now that the codebase has evolved a bit, we might want to change the format to make it a little straightforward.  Some of the elements in the list seems redundant (notably the 5th positional and `:head`), yet the expansion is not handled the same between them.

@myshevchuk suggested that we do some extra stuff in the background to make it more straightforward.

Don't have the time to tackle this right now, but I should have more time next week.

**Comment by myshevchuk** [comment]
I don't think we can easily decouple Org-capture's `template` string (5th positional) and Org-roam's `:head`. They are both essential to their back-ends. What we could do however, we could normalize their appearance to the user and make sure it is correctly translated and passed to `org-roam-capture`.
I'd suggest the following structure and also a unified template syntax.
```
(setq org-roam-bibtex-templates
  '(:key "r"
    :name "reference"
    :template "org-capture template"
    :head "org-roam head"
    :file-name "org-roam file name")     

```

This has a number of potential caveats that will require quite a bit of work, but it seems to me a worthy goal.

**Comment by zaeph** [comment]
The format you propose feels pretty similar to the declarative templates which @progfolio is implementing in [doct](https://github.com/progfolio/doct).  I believe there is a discussion to use it in Org-roam, so we'll have to see how this evolves in the future, but it could definitely be a path of improvement.

**Comment by myshevchuk** [comment]
I noticed `doct` but haven't had a look at it yet. Maybe we shall wait until Org-roam integrates it, so that we do not depend on `doct` directly?

**Comment by zaeph** [comment]
> I noticed `doct` but haven't had a look at it yet. Maybe we shall wait until Org-roam integrates it, so that we do not depend on `doct` directly?

Yes, let's wait on upstream.  It's not as high a priority as fixing the nested captures, so it'll probably take a couple of weeks before we can get to it.

**Comment by myshevchuk** [comment]
org-roam-bibtex-templates (orb-templates) was deprecated in v0.6.
