### ISSUE TITLE
set prefix for created org file or separate directory

### ISSUE THREAD

**Issue by fab6** [org-roam/org-roam-bibtex#192]
Hi,
currently the file naming is based on the bibtex key e.g. like `zhouTotalRadiativeHeat2017.org`.

Is there an option to add a general prefix to the naming e.g. like `lit_` so the file name becomes `lit_zhouTotalRadiativeHeat2017.org`?

And is there an option to define a subdirectory to org-roam standard-directory where all these files are placed?

Thank you in advance!
Fab

**Comment by myshevchuk** [comment]
Hi,

yes, both is possible with configuring the template appropriately. For ORB version <0.6 this can be achieved as follows:

```elisp
(setq orb-templates
  (("r" "ref" plain (function org-roam-capture--get-point) ""
        ;; - files will be placed into "subdir" directory of org-roam-directory
        ;; - files will be prefixed with "lit_" prefix
        :file-name "subdir/lit_${citekey}"    ;; <= adjust the file name to your needs
        :head "#+TITLE: ${title}\n#+ROAM_KEY: ${ref}\n"
        :unnarrowed t)))
```

Please, consider reading README before opening new issues on GitHub. In particular, read carefully the section [Getting Help](https://github.com/org-roam/org-roam-bibtex#getting-help). This question has been asked multiple time on [Discourse](https://org-roam.discourse.group/) and [Slack](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg). Thank you for your understanding.

**Comment by fab6** [comment]
Hi,
thank you for your quick reply and help! And yes, your are right, I did not read it carefully enough, now I see it... excuse  for this.

**Comment by myshevchuk** [comment]
That's fine, no problem.
