### ISSUE TITLE
How can we set the :PROPERTIES: in template?

### ISSUE THREAD

**Issue by quarkquartet** [org-roam/org-roam-bibtex#199]
**Is your feature request related to a problem? Please describe.**
I just upgraded to v2. Looks nice. But it seems the new orb v0.6.0 changes the way we set the template.

For example, previously I use the template here:
https://emacs.stackexchange.com/questions/59126/how-to-configure-org-roam-bibtex-properly

But now my setting is
```emacs-lisp
(use-package! org-roam-bibtex
  :after org-roam
  :config
  (require 'org-ref)
  (require 'ivy-bibtex)
  (setq orb-insert-interface 'ivy-bibtex)
  (setq orb-note-actions-interface 'ivy)
  (setq orb-preformat-keywords '("citekey" "author" "title" "url" "year"))
 (setq org-roam-capture-templates
       '(("r" "bibliography reference" plain
          ""
          :if-new
          (file+head "~/org/literature/${citekey}.org" "#+TITLE: ${title}\n #+AUTHOR: ${author}\n #+URL: ${url}\n #+YEAR: ${year}\n")
          :unnarrowed t)))
    )
```

I found it generates a template in this form：
![image](https://user-images.githubusercontent.com/26316540/126388322-94dff5b3-f8c7-414b-a3f8-7b6ad3ed9ce8.png)

Yes, this agrees with my templates. But what I want is this：
![image](https://user-images.githubusercontent.com/26316540/126388453-32beb3d8-8923-4dfa-bac6-51f521b5c90d.png)

Can I customize some keywords inside the `:PROPERTIES` in the new version? As shown in the figures, in the old version, I can simply set this in template. However in the new version, it seems that it automatically gives a `:PROPERTIES` at head. Is it still possible to customize this?

**Comment by myshevchuk** [comment]
Hi,
first of all, I urge you not to use random Internet blogs to configure ORB, unless you are more or less proficient with Elisp and know what you are doing. The information in such blogs is often outdated and contains mistakes. For example, that StackExchange answer you are referring to is very poor in the sense that its author does not understand how the package works.

Second, I urge you to read the README file for ORB, especially [the Getting Help section](https://github.com/org-roam/org-roam-bibtex#getting-help) section. Long story short, the GitHub issue tracker should only be used to report bugs and request new features. I don't answer general questions here. This is a rule and I'm not going to break it.

It is possible to achieve what you want. Please read [the ORB manual](https://github.com/org-roam/org-roam-bibtex/blob/master/doc/orb-manual.org) and [the Org-roam manual](https://github.com/org-roam/org-roam/blob/master/doc/org-roam.org). You can also ask your question on [Org-roam Discourse](https://org-roam.discourse.group). I and other users will be happy to answer your questions there.

Thank you for your understanding!
