### ISSUE TITLE
Symbol’s function definition is void: orb-note-actions-ivy

### ISSUE THREAD

**Issue by franburstall** [org-roam/org-roam-bibtex#207]
**Describe the bug**
Do `M-x orb-notes-action` and get the error above.

**Expected behavior**
An ivy interface to the actions menu should appear.

**ORB configuration**
```elisp
(use-package org-roam-bibtex
  :ensure t
  :after org-roam ivy-bibtex
  :config
  (setq orb-insert-interface 'ivy-bibtex)
  (setq orb-note-actions-interface 'ivy)
  (add-to-list 'orb-preformat-keywords "year")
  (org-roam-bibtex-mode))
```

**Environment:**
 - ORB commit or MELPA package version:  c13a05b2c855ba1516241d8a1de33bf2c689d6e4
 - Org Roam commit or MELPA package version: 5dce6261a2a45798cdf0c65371b76c83dd5b1de6
 - Org Mode version: 9.4.6-gab9f2a
 - Emacs framework: none
 - Emacs version: 27.2
 - OS: linux

**Comment by franburstall** [comment]
A little more.  The problem goes away if I explicitly require `orb-ivy`.  I note that the `defcustom` setter will do this but, of course, this won't be fired if I just 
```elisp
 (setq orb-note-actions-interface 'ivy)
```
as the manual suggests.

**Comment by myshevchuk** [comment]
Right, this is also discussed in #189. You'll also find a solution there. I really don't have time now and in the next two weeks to make any commits to ORB. I have a deadline to finish my PhD thesis by the end of August. However, pull requests are warmly welcomed.

I'm closing this as a duplicate.
