### ISSUE TITLE
Support :target keyword

### ISSUE THREAD

**Issue by cobac** [org-roam/org-roam-bibtex#209]
org-roam renamed the keyword `:if-new` to `:target`, breaking ORB if the later is used to construct capture templates. Although `:target` is the preferred default, org-roam will support both for some time, and ORB should too.

**Comment by yuuyins** [comment]
https://github.com/org-roam/org-roam-bibtex/blob/c13a05b2c855ba1516241d8a1de33bf2c689d6e4/org-roam-bibtex.el#L478

`(roam-template (plist-get plst :target))` does the job lol

**Comment by yuuyins** [comment]
https://github.com/org-roam/org-roam-bibtex/blob/c13a05b2c855ba1516241d8a1de33bf2c689d6e4/org-roam-bibtex.el#L478

`(roam-template (or (plist-get plst :if-new) (plist-get plst :target)))` seems to do the job

**Comment by myshevchuk** [comment]
Fixed! Thank you @cobac and @yuuyins and sorry it took so long.
