### ISSUE TITLE
bibtex-actions package has changed it's name and variable name

### ISSUE THREAD

**Issue by prashantnag93** [org-roam/org-roam-bibtex#217]
**Describe the bug**
@myshevchuk 
`bibtex-actions-file-open-note-function` has changed to `citar-file-open-note-function` see [this](https://github.com/bdarcus/citar#notes)

kindly add the following  variable in the ORB `(setq citar-file-open-note-function 'orb-citar-edit-note)`

**Comment by chuxubank** [comment]
I just open the #218 to follow this rename, please check if I miss anything.
BTY, `citar-file-open-note-function` is actually `citar-open-note-function` in upstream's code, the previous one maybe a typo in it's README.
Sorry for the various commit ref log, just check the latest one :P

**Comment by myshevchuk** [comment]
@prashantnag93 Thank you for reporting this and sorry for a late response.

@chuxubank Thank you for fixing it! That must be indeed a typo in the README because previously the function was named `bibtex-actions-file-open-note-function`.
