### ISSUE TITLE
orb-note-action: Symbol’s value as variable is void: org-ref-cite-re

### ISSUE THREAD

**Issue by xzz53** [org-roam/org-roam-bibtex#220]
Package versions:

`emacs`:           27.2
`org`:             dbd192bb
`org-ref`:         c71155fc
`org-roam`:        36928d65
`org-roam-bibtex`: d65b70e9

Never used `org-roam-bibtex` before, got this error. This is probably related to https://github.com/jkitchin/org-ref/commit/e0fc517a38ebd2ad9f7264b5accafb7a60f2f533 which removes `org-ref-cite-re`, or I'm just missing something.

**Comment by myshevchuk** [comment]
Hi! Thank you for reporting this and sorry it took so long to fix it - I was pretty busy last two weeks.

The issue should be fixed now. Moreover, `orb-note-actions` now work with three different styles of citation keys in `ROAM_REFS`: Org-ref v2 and v3 as well as Org-cite.
