### ISSUE TITLE
:ROAM_REFS: uses old org-ref format without ampersand

### ISSUE THREAD

**Issue by zipy124** [org-roam/org-roam-bibtex#224]
Not necessarily a bug just unsure if intended?

**Comment by myshevchuk** [comment]
Yes, it is intended. The style can however be easily changed in `orb-citekey-format' - just set your own preferred format string, with ampersand.

P.S. I've just pushed a new commit where `orb-citekey-format` was renamed into `orb-roam-ref-format`. Besides that, this  option can be set to a symbol to choose from one of the three predefined formats: old and new Org-ref formats as well as Org-cite `[cite:@key]` citations.
