### ISSUE TITLE
orb-note-actions Could not retrieve the citekey.  Check ROAM_REFS property of current node

### ISSUE THREAD

**Issue by Jousimies** [org-roam/org-roam-bibtex#227]
This is my org-roam ref file content:
```
# -*- coding:utf-8 -*-
:PROPERTIES:
:ID:       20211118T210955.597044
:ROAM_REFS: cite:hans
:END:
#+title: Yield Line Analysis of the Punching Problem at Slab/Column Intersections
```
I run `M-x orb-note-actions`, the minibuffer echo Could not retrieve the citekey.  Check ROAM_REFS property of current node. 

If I run eval-expression command under the org-roam ref file with `(orb-get-node-citekey)`, it returned `nil`.
If I run with `(org-entry-get (point) "ROAM_REFS")`, it returned `cite:hans`.
If I run with `(org-roam-node-at-point 'assert)`, it returned `#s(org-roam-node "/home/dn/Nextcloud/L.Personal.Galaxy/roam/ref/hans.org" "Yield Line Analysis of the Punching Problem at Slab/Column Intersections" nil (24982 20647 981142 545000) (24982 20647 971142 414000) "20211118T210955.597044" 0 1 nil nil nil nil "Yield Line Analysis of the Punching Problem at Slab/Column Intersections" (("CATEGORY" . "hans") ("ROAM_REFS" . "cite:hans") ("ID" . "20211118T210955.597044") ("BLOCKED" . "") ("FILE" . "/home/dn/Nextcloud/L.Personal.Galaxy/roam/ref/hans.org") ("PRIORITY" . "B")) nil nil nil ("hans"))`

Below is my orb config:
```eslip
(add-to-list 'load-path "~/.emacs.d/site-lisp/packages/org-ref")
(require 'org-ref)
(leaf org-roam-bibtex
  :load-path ("~/.emacs.d/site-lisp/packages/org-roam-bibtex"
	      "~/.emacs.d/site-lisp/packages/helm-bibtex"
	      "~/.emacs.d/site-lisp/packages/parsebib"
	      "~/.emacs.d/site-lisp/packages/biblio"
	      "~/.emacs.d/site-lisp/packages/hydra"
	      )
  :require t bibtex-completion parsebib biblio hydra orb-utils orb-core
  :global-minor-mode org-roam-bibtex-mode
  :custom (orb-note-actions-interface . 'default)
  )
```
My Emacs version `GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4) of 2021-03-27`
My org version `"9.4.4"`

Any suggestion for solve this problem?

**Comment by myshevchuk** [comment]
Hi, this was an error introduced in one of yesterday's commits. I've just fixed it.
