### ISSUE TITLE
:ROAM_REFS: org-ref V3 citations not opened by bibtex-completion notes function

### ISSUE THREAD

**Issue by zipy124** [org-roam/org-roam-bibtex#232]
After commit 5711f45 using orb-roam-ref-format in org-ref-v3 mode correctly sets :ROAM_REFS: to use the V3 style. This means back-links now work correctly. 

However when clicking a citation and choosing the note function using helm-bibtex it does not open an existing note with a V3 style ROAM_REF, instead it will open an existing note if it has the V2 style, or create a new one with a V3 style, thus creating a new note every single time even if a note exists with a V3 ROAM_REF.

**Comment by myshevchuk** [comment]
Hi, I cannot reproduce this. I can open notes with new Org-ref v3 `[[cite:&links]]` from both Org-ref and Helm-bibtex. Do you have `org-roam-bibtex-mode` enabled?

**Comment by zipy124** [comment]
I do have the mode enabled yes.

**Comment by myshevchuk** [comment]
Then try updating both ORB and Org-roam to the latest versions. As said above, I can’t reproduce the issue with my setup, so it must be something with yours but I can’t really debug it with what you’ve provided.

**Comment by zipy124** [comment]
> Then try updating both ORB and Org-roam to the latest versions. As said above, I can’t reproduce the issue with my setup, so it must be something with yours but I can’t really debug it with what you’ve provided.

Updating seems to have fixed the issues, sorry for creating the issue!
