### ISSUE TITLE
Distributed Bibliography?

### ISSUE THREAD

**Issue by jdtsmith** [org-roam/org-roam-bibtex#240]
I have been envisioning a system to entirely supplant Zotero for managing references, which would include persistent links to PDFs, rich field searching over a distributed database of references, and bi-directionally linked notes, right inside the reference nodes themselves.  

The feature that is perhaps relevant to ORB is distributing all the bibliographic data itself over arbitrary files in linkable org-roam nodes.  So bib entries could easily link to(/cite) each other in their notes, use tags, etc.  They'd also then be "self-contained" so you could select a set of them and pass to a student or collaborator, notes intact.  I noticed the quite old org-bibtex supports 2-way transfer between bibtex stanzas and :PROPERTIES drawers, which might provide a reasonable 1st approach for making bib entires self-contained.  I first wanted to ask if this kind of workflow is already possible with ORB, and if not, gauge the level of difficulty of adapting it as a trial.

**Comment by myshevchuk** [comment]
Hi,

I haven't used Org-bibtex myself but I believe there are no obstacles in using it together with ORB. It should be possible to integrate Org-bibtex into Org-roam/ORB templates right away. I mean, just put into the template whatever special tokens, if any, Org-bibtex expects in the PROPERTIES drawers and voilà. It should also be relatively simple to filter off a subset of ORB notes and share it with others using the existing Emacs and external tools, e.g. occur, grep, dired, Org-mode tags and so on. If your notes are in the format compatible with Org-bibtex then the BibTeX records can readily be extracted by your peers.

As for whether ORB will ever provide a functionality similar to Org-bibtex, that is writing to BibTeX files, then my answer is most likely not. ORB is not meant to be a reference manager and as such it will never write to BibTeX files. ORB is about extracting information from BibTeX files and putting it into Org-roam notes. That's it basically. On the other hand, some additional convenience user interface for handling bibliographic Org-roam notes would fit into the existing paradigm and therefore can be developed in future. This may include, for example, special filtering or exporting conveniences. But all such enhancements should be articulated clearly in separate feature requests.

Regarding the more general question of replacing Zotero for managing references, I'm afraid I can't help with that. I haven't been using Zotero for 4 or 5 years now so I just don't understand the problem really. I'm using the BibTeX format and whatever the BibTeX manager currently suits my needs (BibDesk at the moment, but JabRef and/or Ebib are the next candidates as soon as I abandon Mac) while managing my notes with Org-roam/ORB. As I said, I couldn't figure any convincing reasons for using Org-bibtex. The existing level of integration between the tools and formats doesn't make me feel uncomfortable enough for me to want to change anything.

**Comment by jdtsmith** [comment]
Thanks for your thoughts.   I need to think more about this, but in fact I've realized that this may be more of a request for citar or the other tools — to support assembling and working with a "virtual bibtex database" created on the fly from distributed org-roam nodes (and their :PROPERTIES drawers).   

Closing this for now; if I have further relevant thoughts I'll return or open a new request.
