### ISSUE TITLE
API changes in citar

### ISSUE THREAD

**Issue by bdarcus** [org-roam/org-roam-bibtex#244]
First, just a head's up that we're currently working on some major architectural changes in citar:

https://github.com/emacs-citar/citar/pull/634

The API change is moving back to it being citekey-focused.

As part of that, I'm simplifying the note part accordingly, which impacts `orb-citar-edit-note`:

https://github.com/org-roam/org-roam-bibtex/blob/efdac6fe4134c33f50b06a0a6d192003d0e5094c/org-roam-bibtex.el#L1090-L1095

What I _want_ to do: just have note functions take a single argument; the citekey.

But if we do that, this will break.

Thoughts?

**Comment by myshevchuk** [comment]
I'll make the second dummy argument optional to maintain compatibility with previous versions and ensure a smooth transition.

**Comment by myshevchuk** [comment]
Fixed in https://github.com/org-roam/org-roam-bibtex/commit/201262a839db20af2a49165a80f85f82dad159d1.

**Comment by bdarcus** [comment]
Just FYI, there's been some subsequent discussion that may revert my change.

But having entry optional will ensure it works either way.
