### ISSUE TITLE
Considering add a functon to add new node only?

### ISSUE THREAD

**Issue by wztdream** [org-roam/org-roam-bibtex#250]
**Is your feature request related to a problem? Please describe.**

In current version, we can only add a new bibtex related new node by calling `orb-inert-link`, if the node already exist, then it will insert a link, if the node are not exist, then it will add a new node and open it. But in real scenario, user may not sure if the new node exist or not? Simply because the user can not remember all nodes status. Suppose the user only want to add a new node "A" and actually this node already exist but he forgot, and he called `orb-insert-link` and insert a link at point, this is not what the user want.

**Describe the solution you'd like**

define a function something like `orb-add-or-edit-node`, if the node already exist, then open it, if it not exist create it and open it. The point is that the user may not want insert a link.

**Comment by myshevchuk** [comment]
Hi,

simply use Helm-bibtex or Ivy-bibtex or Citar for that. For instance, call `helm-bibtex`, select a reference and press `F8` ("Edit notes"). If `org-roam-bibtex-mode` is on, then if the node already exists, it will be opened, else a new note will be created.

**Comment by myshevchuk** [comment]
Hi,

simply use Helm-bibtex or Ivy-bibtex or Citar for that. For instance, call `helm-bibtex`, select a reference and press `F8` ("Edit notes"). If `org-roam-bibtex-mode` is on, then if the node already exists, it will be opened, else a new note will be created.

**Comment by myshevchuk** [comment]
Hi,

simply use Helm-bibtex or Ivy-bibtex or Citar for that. For instance, call `helm-bibtex`, select a reference and press `F8` ("Edit notes"). If `org-roam-bibtex-mode` is on, then if the node already exists, it will be opened, else a new note will be created.

**Comment by wztdream** [comment]
> Hi,
> 
> simply use Helm-bibtex or Ivy-bibtex or Citar for that. For instance, call `helm-bibtex`, select a reference and press `F8` ("Edit notes"). If `org-roam-bibtex-mode` is on, then if the node already exists, it will be opened, else a new note will be created.

Yes, you are right. My mistake.
