### ISSUE TITLE
[Documentation fix] Citar integration is handled differently now

### ISSUE THREAD

**Issue by bertulli** [org-roam/org-roam-bibtex#257]
Hi all,
I noticed that, according to ORB's README, the integration of ORB with Citar should happen out of the box.
This is no longer the case: as I discovered while trying to make my config work, now Citar requires [a minor modification](https://github.com/emacs-citar/citar/wiki/Notes-configuration#org-roam-bibtex) and [a small add-on package (`citar-org-roam`)](https://github.com/emacs-citar/citar-org-roam). See also [this issue and its answer from bdarcus](https://github.com/emacs-citar/citar/issues/689).
I think this should be included in ORB's README. Could this be possible? I can do a PR if you want.

Thanks for your work!

**Comment by myshevchuk** [comment]
Hi @bertulli, it would be great if you could submit a PR. Please also see [this discussion](https://github.com/org-roam/org-roam-bibtex/discussions/253) for reference.

**Comment by bertulli** [comment]
Thanks, done! Tell me if it's ok for you. 👍
