### ISSUE TITLE
One note file for all bib entries

### ISSUE THREAD

**Issue by mynet1314** [org-roam/org-roam-bibtex#264]
Is there a way to make one note file (i.e. one org file to take note on all my bibliography)?

I prefer storing all notes in one file instead multi files, because I think this way will be helpful for me to manage my notes.

Is there a way to configure this? 

Thanks for any tips.

**Comment by myshevchuk** [comment]
I think yes. Org-roam allows for creating multiple notes within one file. You may want to look in [the Org-roam manual](https://www.orgroam.com/manual.html). Org-roam-bibtex does not add anything here nor does it really care.  Note management is performed by Org-roam.

This tracker is only for bug reports and feature requests/suggestions, please ask questions in [the Org Roam Discourse group](https://org-roam.discourse.group/)
