### ISSUE TITLE
helm-bibtex doesn't work from everywhere when org-roam-bibtex-mode enabled

### ISSUE THREAD

**Issue by P451M** [org-roam/org-roam-bibtex#268]
### Discussed in https://github.com/org-roam/org-roam-bibtex/discussions/267

<div type='discussions-op-text'>

<sup>Originally posted by **P451M** January 27, 2023</sup>
Hi, 

I'm currently getting started with annotated bibliography management with *Spacemacs* and am experimenting with *org-roam-bibtex*. I face the following problem:

1. When `org-roam-bibtex-mode` is disabled I can run `helm-bibtex` within any mode to open the `helm-bibtex` buffer. 
2. When `org-roam-bibtex-mode` is enabled, `helm-bibtex` only seems to work within `org-mode` or `bibtex-mode`. In other modes, as for instance in the *messages* buffer, I get the error: 
`helm-M-x-execute-command: Args out of range: #<buffer *Messages*>, 0, 0` 
 
Is it possible to use `helm-bibtex` from anywhere having `org-roam-bibtex-mode` enabled? Or is that not supported?</div>

**Comment by myshevchuk** [comment]
Should be fixed now.
