### ISSUE TITLE
ORB always prompting for template capture, even if the node already exists

### ISSUE THREAD

**Issue by matogoro** [org-roam/org-roam-bibtex#269]
**Describe the bug**
Hi all, I was wondering if I could get some help with my configuration.  I use a combination of `helm-bibtex`, `org-roam`, and `org-roam-bibtex`.  On Emacs startup, ORB works fine: I can pull up `helm-bibtex` and use "Edit notes" to navigate to the org note files for various BibTeX entries.  I can also appropriately create new `org-capture` templated files for BibTeX entries without notes files.  However, once the first `org-capture` buffer is called, it is called every time ORB is invoked---even if files already exist (it will try to wedge the template into the template that's already there).  Trying to create links with ORB will similarly call `org-capture` every time and will "ruin" things for the rest of the session by calling `org-capture` no matter what.

**To Reproduce**
1. Start Emacs daemon
2. Run `helm-bibtex`
3. Create a new note via "Edit notes" and use the `org-capture` template
4. The `org-capture` template will now run every time, even if the files already exist

Alternatively,
1. Start Emacs daemon
2. Go to an `org-roam` note
3. Run `orb-insert-link`
4. The `org-capture` template will now run every time, even if the files already exist (the links are made correctly and work well, though)

**Expected behavior**
Importantly, I don't use `org-ref`; I'd rather keep citations using the BibTeX `citekey` keyword.  Ideally, I would want to create ORB links using citekeys with discretionary calling of `org-capture` template buffers (only if a new file is needed).  For now, I can perform a workaround using a blank `org` template.

**ORB configuration**
See below for my `org-roam` and `org-roam-bibtex` configuration (minus my keybindings):

```
(use-package org-roam
  :custom
  (org-roam-directory (file-truename "~/Documents/Homework/Zettelkasten/Nodes"))
  (org-roam-completion-everywhere t)
  (org-roam-capture-templates
    `(("r" "Reference" plain
      (file "~/Documents/Homework/Zettelkasten/Templates/reference.org")
       :target (file "Reference/${citekey}.org")
       :unnarrowed t)
      ("b" "Blank Reference Workaround" plain
      (file "~/Documents/Homework/Zettelkasten/Templates/blank.org")
       :target (file "Reference/${citekey}.org")
       :unnarrowed t)))
  :config
  (setq org-roam-mode-sections
        '((org-roam-backlinks-section :unique t)
          org-roam-reflinks-section))
  (org-roam-db-autosync-mode))

(use-package org-roam-bibtex
  :after org-roam helm-bibtex
  :config
  (setq orb-preformat-keywords '("citekey" "author-or-editor-abbrev" "author-or-editor" "date" "title" "url" "keywords" "file")
        orb-process-file-keyword t
        orb-attached-file-extensions '("pdf")
        orb-insert-interface 'helm-bibtex
        orb-insert-link-description 'citekey
        orb-file-field-extensions '("pdf" "epub"))
  (org-roam-bibtex-mode 1))
```

**Environment (please complete the following information):**
 - ORB v0.6.2-20-gc87acc2
 - Org Roam v2.2.2-39-ge738907e
 - Org Mode 9.6.1-gaa2249
 - Vanilla Emacs daemon
 - Emacs version 28.2
 - Void Linux

Thank you in advance!

**Comment by myshevchuk** [comment]
Hi, I cannot reproduce this behaviour. Check wether `org-roam-bibtex-mode` is on. From your configuration above, there is a chance that `org-roam-bibtex-mode` is not being toggled on automatically. You put the call into the `config` section, but this section is executed only after the package has been loaded, yet `org-roam-bibtex-mode` is typically what triggers loading the package... One would typically put the call to `org-roam-bibtex-mode` somewhere else.

**Comment by matogoro** [comment]
Thank you, @myshevchuk!  This is a good start, and I can now get `org-roam-bibtex-mode` to load reliably by invoking `(org-roam-bibtex-mode +1)` *outside* the `use-package` declaration.

However, I'm still having problems with ORB always attempting to capture new notes, whether the note already exists or not.  My setup has a couple oddities like using `straight.el` and not using `org-ref`, which may be contributing factors.  Either way, I am able to reproduce this behavior by evaluating the following in an `emacs -Q` session:

```
;; Set Emacs directory
(setq user-emacs-directory (expand-file-name "~/Uniconfig/Settings/Emacs/"))

;; Bootstrap straight.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Make sure org and use-package are loaded
(straight-use-package 'org)
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)

;; Set up helm-bibtex, org-roam, and ORB
(use-package helm-bibtex
  :config
  (setq bibtex-completion-library-path "~/Multimedia/Literature/SciLi/"
        bibtex-completion-notes-path "~/Documents/Homework/Zettelkasten/Nodes/Reference"
        bibtex-completion-bibliography "~/Multimedia/Literature/SciLi/index.bib"
        helm-bibtex-default-action 'helm-bibtex-open-any
        bibtex-completion-pdf-field "file"
        bibtex-completion-pdf-symbol "#"
        bibtex-completion-notes-symbol "N"
        bibtex-completion-cite-default-command "autocite"
        bibtex-completion-cite-prompt-for-optional-arguments nil))

(use-package org-roam
  :custom
  (org-roam-directory (file-truename "~/Documents/Homework/Zettelkasten/Nodes"))
  (org-roam-completion-everywhere t)
  (org-roam-capture-templates
    `(("r" "Reference" plain
      (file "~/Documents/Homework/Zettelkasten/Templates/reference.org")
       :target (file "Reference/${citekey}.org")
       :unnarrowed t)
      ("b" "Blank Reference Workaround" plain
      (file "~/Documents/Homework/Zettelkasten/Templates/blank.org")
       :target (file "Reference/${citekey}.org")
       :unnarrowed t)))
  :config
  (setq org-roam-mode-sections
        '((org-roam-backlinks-section :unique t)
          org-roam-reflinks-section))
  (org-roam-db-autosync-mode))

(use-package org-roam-bibtex
  :after org-roam
  :config
  (setq orb-preformat-keywords '("citekey" "author-or-editor-abbrev" "author-or-editor" "date" "title" "url" "keywords" "file")
        orb-process-file-keyword t
        orb-attached-file-extensions '("pdf")
        orb-insert-interface 'helm-bibtex
        orb-insert-link-description 'citekey
        orb-file-field-extensions '("pdf" "epub")))

(org-roam-bibtex-mode +1)
```

Interestingly, when I *do* create a new ORB reference note and attempt to save it, I get the following error:

```
Warning (org-roam): /home/USER/Documents/Homework/Zettelkasten/Nodes/Reference/CITEKEY.org:1	Invalid ref cite:CITEKEY, skipping...
```

Notably, the `cite:CITEKEY` portion is under the `ROAM_REFS` tag at the top of the file.  I wonder if these notes are not being properly entered into the `org-roam` database, so ORB is not able to detect already-created notes?  Or do I need `org-ref` or `org-cite` to fix this?

**Comment by myshevchuk** [comment]
Thanks @matogoro for detailed investigations. Yes, it looks like that. However, you don't need to install `org-cite` because it is Org built in. You should only tell ORB to use the Org-cite style citation references in `ROAM_REFS` when creating new notes by setting `orb-roam-ref-format` to `org-cite` . The default is `org-ref-v2` style, but since you don't use Org-ref, you should change it `org-cite`.

**Comment by matogoro** [comment]
Yup, good call---that was the problem.  I knew it was something simple.  For reference, the final code is here:

```
(use-package org-roam-bibtex
  :after org-roam
  :config
  (setq orb-preformat-keywords '("citekey" "author-or-editor-abbrev" "author-or-editor" "date" "title" "url" "keywords" "file")
        orb-process-file-keyword t
        orb-attached-file-extensions '("pdf")
        orb-insert-interface 'helm-bibtex
        orb-insert-link-description 'citekey
        orb-roam-ref-format 'org-cite
        orb-file-field-extensions '("pdf" "epub")))

(org-roam-bibtex-mode +1)
```

Thank you for your help.  Excellent package!

**Comment by myshevchuk** [comment]
Thank you! I'm glad your problem is solved.
