### ISSUE TITLE
Enhance description of package in README.org

### ISSUE THREAD

**Issue by tmalsburg** [org-roam/org-roam-bibtex#31]
Users of plain helm/ivy-bibtex (and perhaps org-ref, not sure) might wonder what this package gives them that they wouldn't get from just setting `bibtex-completion-notes-path` to the value of `org-roam-directory`.

**Comment by zaeph** [comment]
Yeah, I think we've left that job up to Org-roam so far, expecting that users would discover the package from Org-roam rather than `helm-bibtex` or `ivy-bibitex`.

We could make a section on the benefits of the slip-box system for scholarly work, and point to a couple of sources.  I'll keep that in mind and write something out next week, but if anyone wants to give it a shot in the meantime, please do.

**Comment by tmalsburg** [comment]
Sorry, I wasn't clear. I assuming a user who is vaguely familiar with Zettelkasten and org-roam and with helm/ivy-bibtex.  But even these users might not understand, why they need ORB.  If they set `bibtex-completion-notes-path` to `org-roam-directory`.  Their notes will register in org-roam, won't they?

**Comment by zaeph** [comment]
> Sorry, I wasn't clear.

Nah, it's probably me, don't worry.

> I assuming a user who is vaguely familiar with Zettelkasten and org-roam and with helm/ivy-bibtex. But even these users might not understand, why they need ORB.  If they set `bibtex-completion-notes-path` to `org-roam-directory`. Their notes will register in org-roam, won't they?

They would yes, and I see your point now.  We need to emphasise that ORB is about making it more convenient for you to manage your bibliographic notes, and list the the conveniences:
- Template creation that combines `bibtex-completion`'s and Org-roam's
- Commands to filter out references from `org-roam-find-file` to avoid candidate pollution for people managing large libraries.
- Actions similar to those offered by `helm-bibtex` and `ivy-bibtex` accessible directly from the bibliographic note.
- etc.

**Comment by tmalsburg** [comment]
👍

> Template creation that combines bibtex-completion's and Org-roam's

Since org-roam is so new, it would be good to give at least some vague idea of what org-roam templates can do. 

> Actions similar to those offered by helm-bibtex and ivy-bibtex accessible directly from the bibliographic note.

Note that, if point is on a key or bibtex entry (.bib file), helm/ivy-bibtex automatically open search with that entry giving quick access to actions.  In ORB you might want to implement something similar so that users can recycle their muscle memory.

**Comment by zaeph** [comment]
> Note that, if point is on a key or bibtex entry (.bib file), helm/ivy-bibtex automatically open search with that entry giving quick access to actions. In ORB you might want to implement something similar so that users can recycle their muscle memory.

Wow, I didn't know that.  We've got all the infrastructure to do it, so it should be trivial.  I'll see how you do it with `bibtex-mode`.

**Comment by tmalsburg** [comment]
See `bibtex-completion-key-at-point` and the definition of `helm-bibtex`.

**Comment by tmalsburg** [comment]
> Wow, I didn't know that.

This is so Emacs: cool features everywhere but they are difficult to discover because there's not appropriate documentation since devs are too busy writing new features. lol

**Comment by zaeph** [comment]
> See `bibtex-completion-key-at-point` and how that is used in the definition of `helm-bibtex`.

We'll probably need to implement a `funcall` to a `defcustom` as we did with other functions in `bibtex-completion`.

**Comment by zaeph** [comment]
> We'll probably need to implement a `funcall` to a `defcustom` as we did with other functions in `bibtex-completion`.

Something that would allow us to run something here:
https://github.com/tmalsburg/helm-bibtex/blob/16b113692966da9bbe1f9f0ed8dcbfd2db61a7ba/bibtex-completion.el#L1546-L1561

**Comment by tmalsburg** [comment]
Alternatively, we could refactor `bibtex-completion-key-at-point` to be extensible, e.g. via hook functions?  Not sure what the most idiomatic pattern is.

**Comment by zaeph** [comment]
> Alternatively, we could refactor `bibtex-completion-key-at-point` to be extensible, e.g. via hook functions? Not sure what the most idiomatic pattern is.

I think they're practically the same, but I think hooks are more user-oriented, and therefore for more user-oriented command/functions.  Since we've elected to go for `funcall` in previous modifications, I think sticking to it now would be wise.

**Comment by tmalsburg** [comment]
> Since we've elected to go for funcall in previous modifications, I think sticking to it now would be wise.

Good point!

**Comment by zaeph** [comment]
> I'm just a little worried that we might end up having dozens of those defvars.

I think that's the price to pay for modularity, and we'd have to pay it to if we used hooks instead.  As much as this would _clutter_ `bibtex-completion`, it makes it a whole lot straightforward for ORB to patch into it rather than having to shadow the entire function, which might lead to problems when there are changes upstream.

> This is so Emacs: cool features everywhere but they are difficult to discover because there's not appropriate documentation since devs are too busy writing new features. lol Sorry for the digression.

[Story of our lives right there, really](https://xkcd.com/378/).

**Comment by tmalsburg** [comment]
> I think that's the price to pay for modularity, and we'd also have to pay it to if we used hooks instead.

Yes, and there are probably ways to use that new defvar for good purpose within bibtex-completion as well.  By the way, I think it should be a list of functions that we work through until a bib entry is identified.  This list could then be configured on a buffer-by-buffer basis depending on major mode and other circumstances.

**Comment by zaeph** [comment]
> Yes, and there are probably ways to use that new defvar for good purpose within bibtex-completion as well. By the way, I think it should be a list of functions that we work through until a bib entry is identified. This list could then be configured on a buffer-by-buffer basis depending on major mode and other circumstances.

Sounds good.  I'll draft something up next week, and I'll PR.

**Comment by zaeph** [comment]
I added a commented demonstration with 1edb44684b4a0e2258256e53a96b22347b97b2f1 which should help people figure out what the package do.  I did it quickly and without much preparation, but I think it'll give some interesting pointers to people.

**Comment by tmalsburg** [comment]
Very nice presentation! Thanks for adding it.
