### ISSUE TITLE
error: org-roam-bibtex-mode: Symbol’s value as variable is void: bibtex-completion-find-note-functions

### ISSUE THREAD

**Issue by Gahamelas** [org-roam/org-roam-bibtex#41]
Hi, 
I am experiencing this error when loading Emacs. 
I installed the package vi Melpa and added

```
(require 'org-roam-bibtex)
(add-hook 'after-init-hook #'org-roam-bibtex-mode)
```

To my init.
Thanks in advance, 
GM

**Comment by zaeph** [comment]
Hi there.

You need to update your `helm-bibtex`/`ivy-bibtex` & `bibtex-completion`.  We rely on code that was recently pushed to those directories.

Let me know if it works after that.

**Comment by Gahamelas** [comment]
Thanks for the prompt reply. How do I update this? You mean, using `M-x package-reinstall`?

**Comment by zaeph** [comment]
You could `M-x package-list-packages`, find the packages I've mentioned above, marked them as _to-install_ by pressing `i`, and then `execute` with `x`.

**Comment by zaeph** [comment]
Or, more simply, `M-x package-list-packages`, press `U` to mark all the packages with updates, then press `x`.

**Comment by Gahamelas** [comment]
Thanks, newbie here :)
