### ISSUE TITLE
failed to define function orb-note-actions

### ISSUE THREAD

**Issue by qlibp** [org-roam/org-roam-bibtex#59]
I add the following code in at the end of my .doom.d/init.el file
```
(use-package org-roam-bibtex
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :bind (:map org-mode-map
         (("C-c n a" . orb-note-actions))))
```
Running ```M-x orb-note-actions``` and I get the following error
**failed to define function orb-note-actions**

Aside:
When i install orb with package-list, it shows **2 files ignored**.

**Comment by myshevchuk** [comment]
Hi! I'm also using doom and could not reproduce your issue. With this snippet, `C-c n a` is bound to `orb-note-actions` and executes well for me.

Normally, you do not put any configuration in `init.el`, you should use `config.el` for that.
Also, as far as I know, you should not use `package.el` together with `doom`.
