### ISSUE TITLE
Citing a webpage

### ISSUE THREAD

**Issue by qlibp** [org-roam/org-roam-bibtex#61]
Is there any workaround for citing a webpage with org-roam-bibtex?

For now, I could use [this web service](https://zbib.org/) to generate a bibtex citation of a web page.

Thanks!

**Comment by myshevchuk** [comment]
Hi!

`org-roam-bibtex` is not used to cite anything. It does not generate any BibTeX data. It's task is very different: it uses processes existing BibTeX data stored in the form of a BibTeX file and helps to automate some BibTeX-related tasks in the context of a `org-roam` note using that information.

To generate or download any BibTeX citation, please use tools specialized for those tasks.

**Comment by qlibp** [comment]
i see, thanks!
