### ISSUE TITLE
Can't get default orb-template to work when adding a note from bibliography

### ISSUE THREAD

**Issue by bsag** [org-roam/org-roam-bibtex#63]
I had this working, and now it's not working :-(

What I expect:
- Use ivy-bibtex to find a reference without a note currently
- C-o, use Edit note option to edit a note
- Get a new note with contents defined by the default orb-templates value 

What I get:
- Contents with only a title, not defined by any format I can find:
"#+TITLE: Notes on: [author list...] (year). Title"

When I use C-h v to find the current value of orb-templates I get:

`(("r" "ref" plain #'org-roam-capture--get-point "" :file-name "${citekey}" :head "#+TITLE: ${title}\n#+ROAM_KEY: ${ref}\n" :unnarrowed t))`

If I eval `(orb-edit-notes "zuninoAlouattaCarayaRelations2001")` in a scratch buffer, I get a new note with the contents defined correctly by the orb-templates default value above.

I'm using Doom Emacs, and the relevant use package part in my config is:

```lisp
(use-package! org-roam-bibtex
  :after org-roam
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :bind (:map org-mode-map
         ("s-b" . orb-note-actions))
  )
```

I've unpinned `:tools biblio` and made sure that I have the latest versions of helm/ivy-bibtex and bibtex-completion.

Any help much appreciated! I love this package and really want to make it work for my note-taking on references.

**Comment by bsag** [comment]
Just to update, while poking around I found out where the mystery file contents came from. It's ` bibtex-completion-notes-template-multiple-files`. I confirmed that by setting it to different contents and seeing that when I edit a note from ivy-bibtex, I get that format, and when I manually eval `(orb-edit-notes KEY)` or `(orb-notes-fn)` using the same key, I get to choose my custom-defined orb-templates which get created properly.

**Comment by myshevchuk** [comment]
Hi! Thank you very much for your kind words!

It is possible `org-roam-bibtex-mode` is not turned on. Try manually turning it on `M-x org-roam-bibtex-mode`. If it works, then it is most probably a problem with your config. Check the value of `bibtex-completion-find-note-functions`.
Its top element (car of the list) should be `orb-find-note-file`.

If that doesn't work, please try unpinning `org-roam` and updating your packages. We closely follow `org-roam` upstream and `org-roam` pinned in Doom Emacs often lags behind substantially. As far as I remember, there've been recent changes in both packages that affected `orb-find-note-file`. If you have an older version of `org-roam`, this is a very likely cause of your issue.

**Comment by bsag** [comment]
Thanks for the help @myshevchuk!

Here's what I tried following your help:

- I had been checking that org-roam-bibtex-mode was turned on. Oddly (and I was going to ask about this too) the hook in my org-roam-bibtex use-package block above does not seem to work automatically, so I always have to turn it on manually. Anyway, it has bee non when I've been running these commands.
- I checked to see what the value of `bibtex-completion-find-note-functions` was and was surprised that `C-h v` couldn't find it (only a similar command to find addtional PDFs).
- So I've now unpinned both the doom biblio flag (:tools biblio) and org-roam, and got the master version of those packages. However, refreshing everything and restarting I'm getting exactly the same behaviour as before, and I seemingly still don't have `bibtex-completion-find-note-functions`.
- One additional wrinkle: When I insert a new `cite:foobar2000` link (for a reference which doesn't have an org-roam-bibtex note yet), and click that link, the helm interface (not ivy for some reason, like the other prompts) pops up. When I select 'Add note' in that, it pops up the org-roam-bibtex capture chooser, and the capture templates I have now set up in org-roam-bibtex work fine.

So I seem to have a partially broken config for some reason. I can post the relevant bits if it would be useful for you to see parts of my config?

Thanks again for your help!

**Comment by myshevchuk** [comment]
That's definitely a problem with your setup, although not necessarily with `config.el` since it used to work before. Such weird behaviour is often a result of loading issues, which in turn are caused by stale `*.elc` files. Chances are you recently did `doom upgrade` after a relatively long time since the last upgrade and then things broke.  There are too many packages involved and interconnected, so I'd advise you to remove completely `.local/straight/` directory from your Doom installation directory, run `doom upgrade` and try to reproduce the issue with a refreshed setup.

**Comment by bsag** [comment]
That seems to fix the main problem! I had actually wiped `.local/straight` at some point when trying to fix it, but it obviously got messed up again somewhere along the line.

I also unpinned `company-org-roam` just to make sure that all the related packages are at their latest versions in Doom when I update.

My templates now work! I still seem to have to manually activate `org-roam-bibtex-mode`, but that's a relatively minor thing.

Thanks for the help!

**Comment by myshevchuk** [comment]
Good to hear!

> I still seem to have to manually activate `org-roam-bibtex-mode`

This seems to be related to your `config.el` or any personal extensions. The `use-package` statement above works well for me. Maybe the loading order of other `org`-related packages. Doom is a beast that needs taming.

**Comment by bsag** [comment]
I'm sure that's it - thanks, I'll close this now.
