### ISSUE TITLE
Symbol's function definition is void: org-roam-capture--capture

### ISSUE THREAD

**Issue by nathanaelbosch** [org-roam/org-roam-bibtex#70]
I am using both `org-roam` and `org-roam-bibtex` from MELPA on Spacemacs, installed by adding them to `dotspacemacs-additional-packages` and configuring things inside `dotspacemacs/user-config`.
`org-roam` works fine on it's own, but I am unable to open notes with `org-roam-bibtex`, due to
```
Symbol's function definition is void: org-roam-capture--capture
```

I saw on the `org-roam` github, that the master branch does indeed contain a `org-roam-capture--capture` function. Could it be that the `org-roam-bibtex` version on MELPA uses functionality, that the `org-roam` version on MELPA does not yet provide (and thus requires users to install `org-roam` through github)? If not, how can I fix this issue?

**Comment by zaeph** [comment]
Hi there.

We haven't touched `org-roam-capture--capture` in a while, so I doubt this is coming from this.

However, I suspect that it might be coming from the order in which your require packages, namely that you're requiring ORB before Org-roam.  I'm not sure how `spacemacs` handles the loading and the requirement of its packages, but you should be able to find the information online.  It might just be a matter of switching the two around in your config.

**Comment by nathanaelbosch** [comment]
Hi and thanks for your reply!

`org-roam-capture--capture` comes from org-roam and not from ORB, right? I can not find it through `describe-function` at all (neither in the org-roam package files I have locally), therefore I guess I have a wrong/old org-roam version, and the order should probably not change that.

But at the same time this means, that the org-roam version on MELPA is definitely up-to-date enough to contain `org-roam-capture--capture`? Then I might need to find out which version I am using and how I can upgrade to a newer version.

**Comment by zaeph** [comment]
> But at the same time this means, that the org-roam version on MELPA is definitely up-to-date enough to contain `org-roam-capture--capture`? Then I might need to find out which version I am using and how I can upgrade to a newer version.

There doesn't seem to be any problem coming from MELPA: I've checked my own MELPA version, and it had `org-roam-capture--capture`.  Seems like a weird problem with the updating of your packages, or that it's getting shadowed by something.  When you `describe-function`, check the path of the file to which it links you to ascertain that it's in your `.emacs.d/elpa`.

**Comment by nathanaelbosch** [comment]
Updating my packages manually solved the issue. Org-roam is now up-to-date and contains `org-roam-capture--capture`, and thus ORB seems to work. Thanks for your help, and I'm looking forward to start using ORB! :)
