### ISSUE TITLE
Installation instructions for Doom Emacs

### ISSUE THREAD

**Issue by acosmicjoke** [org-roam/org-roam-bibtex#76]
I tried getting org-roam-bibtex to work together with bibtex-completion, but I ran into some problems. 
If I use the example configuration from the documentation and load the package after org-roam, what happens is that trying to use ivy-bibtex or helm-bibtex results in the error in the title. I thought maybe it's because org-roam-bibtex is getting loaded before bibtex-completion, so I added `:after bibtex-completion` to my use-package block. With this, ivy-bibtex and helm-bibtex actually work, but when I turn on org-roam-bibtex-mode I still get the same error message. (The mode does turn on though.) It sounds like the package doesn't load completely for some reason, and it does work only partially. For example, I do get backlinks for the citations in my notes, but If I try to create a new note file for a bibliography entry from helm-bibtex or ivy-bibtex, the template in orb-templates is not getting used. What works instead is putting the template in the variable `bibtex-completion-notes-template-multiple-files`. Did I just misunderstand this and the template in orb-templates gets used only if I create a note file with some other function? The `orb-process-file-field` helper function does not work either. 
I'm using doom emacs, and the relevant part of my configuration file looks like this:

    (use-package! org-roam-bibtex
     :after (bibtex-completion)
      :hook (org-roam-mode . org-roam-bibtex-mode)
      :config
      (setq orb-preformat-keywords
       '("=key=" "title" "url" "file" "author-or-editor" "keywords"))
      (setq orb-templates
            `(("r" "ref" plain (function org-roam-capture--get-point)
               ""
               :file-name "literature/${slug}"
               :head ,(concat
                       "#+title: ${=key=}: ${title}\n"
                       "#+roam_key: ${ref}\n\n"
                       "* ${title}\n"
                       "  :PROPERTIES:\n"
                       "  :Custom_ID: ${=key=}\n"
                       "  :URL: ${url}\n"
                       "  :AUTHOR: ${author-or-editor}\n"
                       "  :NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
                       "  :NOTER_PAGE: \n"
                       "  :END:\n")
               :unnarrowed t)))
      )

     (use-package! bibtex-completion
       :defer
       :config
       (setq bibtex-completion-additional-search-fields '(keywords)
             bibtex-completion-pdf-field "file"))
        (setq bibtex-completion-notes-path "~/Dropbox/Org/notes/literature"
                bibtex-completion-bibliography "~/Dropbox/Org/mainbibfile.bib"
                bibtex-completion-library-path "~/Dropbox/Research/Papers"
                bibtex-completion-pdf-field "file"
                bibtex-completion-notes-template-multiple-files
                (concat
                 "#+title: ${title}\n"
                 "#+roam_key: cite:${=key=}\n"
                 "* ${title}\n"
                 ":PROPERTIES:\n"
                 ":Custom_ID: ${=key=}\n"
                 ":NOTER_DOCUMENT: ~/Dropbox/Research/Papers/${=key=}.pdf\n"
                 ":AUTHOR: ${author-abbrev}\n"
                 ":JOURNAL: ${journaltitle}\n"
                 ":DATE: ${date}\n"
                 ":YEAR: ${year}\n"
                 ":DOI: ${doi}\n"
                 ":URL: ${url}\n"
                 ":END:\n\n"))

**Comment by myshevchuk** [comment]
Hi, it would be very helpful if you could provide the error message. Use `toggle-debug-on-error` or run Emacs with the `--debug-init` flag. Also make sure that you have the latest versions of `org-roam`, `org-roam-bibtex`, `bibtex-completion` installed. Put this into `packages.el` : `(unpin! org-roam company-org-roam bibtex-completion ivy-bibtex helm-bibtex)`.

**Comment by myshevchuk** [comment]
`org-roam-bibtex` should be loaded after `org-roam`. Also in your `use-package! bibtex-completion`, shouldn't it be `:defer t`?

**Comment by myshevchuk** [comment]
#75

**Comment by acosmicjoke** [comment]
> #75
Ah yes, somehow I missed this one. 
The error message I got with --debug-init is the same as in this bug report. What happens is that I used the biblio module in doom emacs which pins bibtex-completion and ivy-bibtex to an older version. Things work after unpinning.

By the way, org-ref only seems to work properly for me if I add an `:after org-roam-bibtex` to its use-package block. Is org-roam bibtex supposed to be loaded before the packages it modifies?

**Comment by myshevchuk** [comment]
It should make no difference and work both ways. What exactly does not work for you?

**Comment by acosmicjoke** [comment]
>It should make no difference and work both ways. What exactly does not work for you?

I had some issues with nothing happening when I hit enter when the point is on a citation in org-mode, when normally org-ref would ask me what I want to do with it in a hydra window. It was probably caused by something else because now I can't reproduce it by removing the `:after` part.

**Comment by myshevchuk** [comment]
I'll reopen this issue as a reminder to add Doom Emacs installation instructions
