### ISSUE TITLE
"Immediate" version of org-roam-bibtex-insert-non-ref?

### ISSUE THREAD

**Issue by jmburgos** [org-roam/org-roam-bibtex#77]
Hi,

Would it be possible to have an "Immediate" version of `org-roam-bibtex-insert-non-ref`, analogous to `org-roam-insert-immediate`?  The idea is to be able to insert a link without having to go through the "capture template" buffer.   This is only for the case in which we are using a single capture template in `org-roam-capture-templates` .

Thanks!!!

**Comment by myshevchuk** [comment]
Hi, could you provide a workflow example of what exactly you are trying to achieve?

**Comment by myshevchuk** [comment]
Would I be right saying that you'd like to run `orb-insert-non-ref` to get a list of notes that are not bibliography notes, then after not having found the note you type a new title, press `enter` and have a new link inserted using `org-roam-capture-ref-templates`?

**Comment by jmburgos** [comment]
Yes.  With the new `org-roam-insert-immediate`, if I type the name of a note that I don't have yet, it gets created silently in the background using the only template that I have in `org-roam-capture-templates`, and I get the link to the new note.   I do not see the "Capture Template" buffer, and don't need to type C-c C-c to continue writting.

**Comment by myshevchuk** [comment]
It doesn't seem to me justified to create yet another "insert" function tailored to a single very specific task, which is actually a subtask of another already existing function. Spawning such "subtask" functions violates the DRY principle and ultimately leads to problems with maintenance, extensibility, scalability, etc.

A solution would be to re-use `orb-insert-non-ref` with the universal prefix argument C-u (or rather C-u C-u for single C-u is already used to insert lowercase link description). This can easily be added.

Until then, you can use this custom function in your config:

```elisp
(defun my/orb-insert-non-ref-immediately (prefix)
  "Insert non bibliography link immediately"
  (interactive "P")
  (let ((org-roam-capture-templates (list org-roam-capture-immediate-template)))
    (org-roam-insert prefix (orb--get-non-ref-path-completions))))
```

Adjust `org-roam-capture-immediate-template` to your needs.

**Comment by jmburgos** [comment]
Thank you @myshevchuk, yes, it makes complete sense. I was asking because org-roam has a `org-roam-insert-immediate` function that was added recently.  But I just learned that in org-roam the effect I want can be achieved by having a single template that includes the  `:immediate-finish t` option.  The same thing works in org-roam-bibtex.  So there is no need to change anything.

**Comment by myshevchuk** [comment]
@jmburgos FYI. `org-roam`'s capture process responsible for creating new notes is built on top of `org-capture`, which is a very powerful and feature-rich machinery. As far as I know, everything described in the doc-string to `org-capture-templates` should also work for `org-roam-capture-templates` (and `orb-templates` for that matter). The only thing, which is hard-coded and should not be changed is the capture destination, the fourth element of the `org-roam-capture-templates` list, `(function org-roam-capture--get-point)`. 

It is implied that users will refer to `org-capture` docs for more information on how to use the templates, although I'm not sure whether this is stated somewhere explicitly. `org-roam-capture` extends `org-capture` with a few convenience features like custom header, file name, and an additional type of prompt wildcards. `org-roam-bibtex` adds the BibTeX-related functionality. These extensions are pretty well explained in our documentation.

**Comment by jmburgos** [comment]
Yes, I am aware of that.  What happened is that I had a mistake in my template that did not allowed the `:immediate-finish t` option to work, and because `org-roam` provided an "immediate" function I assumed that some changes were done under the hood.  But everything is clear and working now.  My apologies for the noise.
