### ISSUE TITLE
Theme question

### ISSUE THREAD

**Issue by matthewdeancooper** [org-roam/org-roam-bibtex#92]
Package looks great. Wondering what theme is being used in the GIF and video?

**Comment by myshevchuk** [comment]
@matthewdeancooper I'm glad you like the package. @zaeph did the recordings, he might know. 

If you don't have any issues related to `org-roam-bibtex`, please consider asking questions in our [Slack channel](https://join.slack.com/t/orgroam/shared_invite/zt-deoqamys-043YQ~s5Tay3iJ5QRI~Lxg) or on [Discourse](https://org-roam.discourse.group/)

**Comment by matthewdeancooper** [comment]
Thanks for the fast reply! Ill forward my question to zaeph in the slack channel.
